server:
    port: 9001

spring:
        application:
            name: PRODUCT-SERVICE
eureka:
        client:
            serviceUrl:
                defaultZone: http://localhost:8761/eureka/
                register-With-Eureka: true
                fetch-Registry: true
                instance:
                    hostname: localhost







